site_name: 일기는 일기장에
site_url: https://fromitive.github.io/fromitive-diary
site_author: fromitive
site_description: >-
  개인적인 이야기

nav:
  - Home : index.md
  - Diary : diary.md
theme:
  name: material
  icon:
    logo : material/shark
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: light blue
    - scheme: slate 
      toggle:
        icon: material/brightness-3
        name: Switch to light mode    
      primary: custom
      accent: light blue
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

plugins:
  - social
  - search:
      lang:
        - en
        - ko
  - blogging:
      # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
      categories:
        - name: diary
          dirs:
            - diary
          paging: true
          size : 3
          show_total : true
   
      # GLOBAL CONFIG: configs apply to all categories
      time_format: '%Y-%m-%d %H:%M'
      meta_time_format: '%Y-%m-%d %H:%M'
      features:
        tags:
          index_page: tags.md
          insert: bottom
        
      locale: ko_KR

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fromitive
    - icon: fontawesome/brands/hackerrank
      link: https://www.hackerrank.com/fromitive
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%EB%AC%B4%EC%86%A1-%EC%9D%B4-7b6b681b9/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

## google analytics
copyright: |
  &copy; 2023 <a href="https://github.com/fromitive"  target="_blank" rel="noopener">백상아리(fromitive@gmail.com)</a>